"""create_metrics_in_30_seconds

Revision ID: 1e46d7f66c94
Revises: 
Create Date: 2026-03-06 02:12:24.873653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e46d7f66c94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_in_30_seconds',
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('product_category', sa.String(length=400), nullable=False),
    sa.Column('revenue_per_window_per_category', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('avg_order_value_per_category', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_volume_per_continent', sa.Integer(), nullable=False),
    sa.Column('unique_products_ordered_per_window', sa.Text(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('window_start', 'product_category')
    )
    op.create_index('idx_product_category', 'metrics_in_30_seconds', ['product_category'], unique=False)
    op.create_index('idx_window_start', 'metrics_in_30_seconds', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_window_start', table_name='metrics_in_30_seconds')
    op.drop_index('idx_product_category', table_name='metrics_in_30_seconds')
    op.drop_table('metrics_in_30_seconds')
    # ### end Alembic commands ###
