"""order_metrics

Revision ID: 4161c77ba0bc
Revises: 
Create Date: 2026-03-06 09:52:07.526165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4161c77ba0bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_metrics',
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('unique_products', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('top_continent', sa.String(length=50), nullable=True),
    sa.Column('top_gender', sa.String(length=20), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('window_start', 'product_category')
    )
    op.create_index('product_category_idx', 'order_metrics', ['product_category'], unique=False)
    op.create_index('window_start_idx', 'order_metrics', ['window_start'], unique=False)
    op.drop_index(op.f('idx_product_category'), table_name='metrics_in_30_seconds')
    op.drop_index(op.f('idx_window_start'), table_name='metrics_in_30_seconds')
    op.drop_table('metrics_in_30_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_in_30_seconds',
    sa.Column('window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('product_category', sa.VARCHAR(length=400), autoincrement=False, nullable=False),
    sa.Column('revenue_per_window_per_category', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('avg_order_value_per_category', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('order_volume_per_continent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unique_products_ordered_per_window', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('loaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('window_start', 'product_category', name=op.f('metrics_in_30_seconds_pkey'))
    )
    op.create_index(op.f('idx_window_start'), 'metrics_in_30_seconds', ['window_start'], unique=False)
    op.create_index(op.f('idx_product_category'), 'metrics_in_30_seconds', ['product_category'], unique=False)
    op.drop_index('window_start_idx', table_name='order_metrics')
    op.drop_index('product_category_idx', table_name='order_metrics')
    op.drop_table('order_metrics')
    # ### end Alembic commands ###
